apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  #lables of deployment
  labels:
    app: nginx
    tier: frontend
    purpose: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      purpose: deployment
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        purpose: deployment
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector: #lables are usedas a
    app: nginx
    tier: frontend
    purpose: deployment
  ports:
  - protocal: TCP
    port: 80 # service port
    targetPort: 80
    nodePort: 30007